trustgrid/docs

content/en/release-notes/cloud/april-2023-3/index.md
Get rid of sub-branch. Don't think that ideal will really work
=> Audit-improvement

content/en/help-center/support-responsibility-matrix/index.md
=> Matrix Edit

content/en/docs/api/index.md, content/en/docs/user-management/API-access/index.md, swagger/swagger.yml
=> add link to API access from swagger page

content/en/release-notes/node/oct-2023-1-minor/index.md
Adds release notes for SNMP fix
=> release notes

content/en/tutorials/deployments/deploy-aws-ami/index.md
=> add multi-region cf templates

layouts/shortcodes/field.html
=> pad top margin to allow for fixed navbar

static/swagger.json, swagger/main.go
=> add port forwarding to swagger

static/swagger.json, swagger/main.go
=> add clients to gateway config docs

content/en/help-center/kb/site-requirements/index.md
not sure why UDP was listed for control plane
=> remove UPD control plane

content/en/tutorials/deployments/deploy-aws-ami/index.md
=> remove cloudwatch agent related info

layouts/shortcodes/codeblock.html
=> fix copy button to be darker when pressed

swagger/main.go, swagger/swagger.yml
=> clarify node/agent api calls

swagger/swagger.yml
=> add service name to swagger example and fix type

swagger/swagger.yml
=> add sourceblock to connector swagger

swagger/main.go
=> add type to node reply

content/en/docs/operations/flow-logs/index.md
Fixing the org ID in the example and add note to just copy from the portal
=> fix org ID

static/swagger.yml
=> clarify update node api

content/en/release-notes/cloud/2025-03/index.md
=> c-5.27.1 release notes

static/swagger.yml
=> add order fields to swagger

.gitignore, content/en/docs/idps/azure-idp-fields/index.md
Added section on changing the secret and updated some sections for clarity based on Cody suggestions.
=> 560-azure-ad

content/en/tutorials/deployments/deploy-azure/_index.md
Add new regions and sort the list
=> update azure regions
